<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\Megasena;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>megasena.ApostaResponse</code>
 */
class ApostaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 numeros = 1;</code>
     */
    private $numeros;
    /**
     * Generated from protobuf field <code>string data_geracao = 2;</code>
     */
    protected $data_geracao = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $numeros
     *     @type string $data_geracao
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Megasena::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 numeros = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNumeros()
    {
        return $this->numeros;
    }

    /**
     * Generated from protobuf field <code>repeated int32 numeros = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNumeros($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->numeros = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data_geracao = 2;</code>
     * @return string
     */
    public function getDataGeracao()
    {
        return $this->data_geracao;
    }

    /**
     * Generated from protobuf field <code>string data_geracao = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDataGeracao($var)
    {
        GPBUtil::checkString($var, True);
        $this->data_geracao = $var;

        return $this;
    }

}

