<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\Megasena;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>megasena.ApostaRequest</code>
 */
class ApostaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 quantidade_dezenas = 1;</code>
     */
    protected $quantidade_dezenas = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $quantidade_dezenas
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Megasena::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 quantidade_dezenas = 1;</code>
     * @return int
     */
    public function getQuantidadeDezenas()
    {
        return $this->quantidade_dezenas;
    }

    /**
     * Generated from protobuf field <code>int32 quantidade_dezenas = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantidadeDezenas($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantidade_dezenas = $var;

        return $this;
    }

}

