<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\Megasena;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>megasena.SimulacaoResponse</code>
 */
class SimulacaoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 total_tentativas = 1;</code>
     */
    protected $total_tentativas = 0;
    /**
     * Generated from protobuf field <code>double tempo_segundos = 2;</code>
     */
    protected $tempo_segundos = 0.0;
    /**
     * Generated from protobuf field <code>repeated int32 numeros = 3;</code>
     */
    private $numeros;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total_tentativas
     *     @type float $tempo_segundos
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $numeros
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Megasena::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 total_tentativas = 1;</code>
     * @return int|string
     */
    public function getTotalTentativas()
    {
        return $this->total_tentativas;
    }

    /**
     * Generated from protobuf field <code>int64 total_tentativas = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalTentativas($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_tentativas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tempo_segundos = 2;</code>
     * @return float
     */
    public function getTempoSegundos()
    {
        return $this->tempo_segundos;
    }

    /**
     * Generated from protobuf field <code>double tempo_segundos = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTempoSegundos($var)
    {
        GPBUtil::checkDouble($var);
        $this->tempo_segundos = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 numeros = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNumeros()
    {
        return $this->numeros;
    }

    /**
     * Generated from protobuf field <code>repeated int32 numeros = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNumeros($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->numeros = $arr;

        return $this;
    }

}

