<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\Megasena;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>megasena.SimulacaoRequest</code>
 */
class SimulacaoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int32 dezenas_alvo = 1;</code>
     */
    private $dezenas_alvo;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $dezenas_alvo
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Megasena::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 dezenas_alvo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDezenasAlvo()
    {
        return $this->dezenas_alvo;
    }

    /**
     * Generated from protobuf field <code>repeated int32 dezenas_alvo = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDezenasAlvo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->dezenas_alvo = $arr;

        return $this;
    }

}

