<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\GPBMetadata;

class Megasena
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ô
megasena.protomegasena"+
ApostaRequest
quantidade_dezenas ("7
ApostaResponse
numeros (
data_geracao (	"(
SimulacaoRequest
dezenas_alvo ("V
SimulacaoResponse
total_tentativas (
tempo_segundos (
numeros (2û
MegasenaService@
GerarAposta.megasena.ApostaRequest.megasena.ApostaResponseI
SimularSorteio.megasena.SimulacaoRequest.megasena.SimulacaoResponseBBZmegasena-server/proto App\\Grpc\\Megasena‚App\\Grpc\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

