<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: megasena.proto

namespace App\Grpc\GPBMetadata;

class Megasena
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Š
megasena.protomegasena"+
ApostaRequest
quantidade_dezenas ("7
ApostaResponse
numeros (
data_geracao (	2S
MegasenaService@
GerarAposta.megasena.ApostaRequest.megasena.ApostaResponseB+ÊApp\\Grpc\\MegasenaâApp\\Grpc\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

