// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: megasena.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MegasenaService_GerarAposta_FullMethodName    = "/megasena.MegasenaService/GerarAposta"
	MegasenaService_SimularSorteio_FullMethodName = "/megasena.MegasenaService/SimularSorteio"
)

// MegasenaServiceClient is the client API for MegasenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MegasenaServiceClient interface {
	GerarAposta(ctx context.Context, in *ApostaRequest, opts ...grpc.CallOption) (*ApostaResponse, error)
	SimularSorteio(ctx context.Context, in *SimulacaoRequest, opts ...grpc.CallOption) (*SimulacaoResponse, error)
}

type megasenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMegasenaServiceClient(cc grpc.ClientConnInterface) MegasenaServiceClient {
	return &megasenaServiceClient{cc}
}

func (c *megasenaServiceClient) GerarAposta(ctx context.Context, in *ApostaRequest, opts ...grpc.CallOption) (*ApostaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApostaResponse)
	err := c.cc.Invoke(ctx, MegasenaService_GerarAposta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *megasenaServiceClient) SimularSorteio(ctx context.Context, in *SimulacaoRequest, opts ...grpc.CallOption) (*SimulacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulacaoResponse)
	err := c.cc.Invoke(ctx, MegasenaService_SimularSorteio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MegasenaServiceServer is the server API for MegasenaService service.
// All implementations must embed UnimplementedMegasenaServiceServer
// for forward compatibility.
type MegasenaServiceServer interface {
	GerarAposta(context.Context, *ApostaRequest) (*ApostaResponse, error)
	SimularSorteio(context.Context, *SimulacaoRequest) (*SimulacaoResponse, error)
	mustEmbedUnimplementedMegasenaServiceServer()
}

// UnimplementedMegasenaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMegasenaServiceServer struct{}

func (UnimplementedMegasenaServiceServer) GerarAposta(context.Context, *ApostaRequest) (*ApostaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GerarAposta not implemented")
}
func (UnimplementedMegasenaServiceServer) SimularSorteio(context.Context, *SimulacaoRequest) (*SimulacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimularSorteio not implemented")
}
func (UnimplementedMegasenaServiceServer) mustEmbedUnimplementedMegasenaServiceServer() {}
func (UnimplementedMegasenaServiceServer) testEmbeddedByValue()                         {}

// UnsafeMegasenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MegasenaServiceServer will
// result in compilation errors.
type UnsafeMegasenaServiceServer interface {
	mustEmbedUnimplementedMegasenaServiceServer()
}

func RegisterMegasenaServiceServer(s grpc.ServiceRegistrar, srv MegasenaServiceServer) {
	// If the following call panics, it indicates UnimplementedMegasenaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MegasenaService_ServiceDesc, srv)
}

func _MegasenaService_GerarAposta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApostaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MegasenaServiceServer).GerarAposta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MegasenaService_GerarAposta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MegasenaServiceServer).GerarAposta(ctx, req.(*ApostaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MegasenaService_SimularSorteio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MegasenaServiceServer).SimularSorteio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MegasenaService_SimularSorteio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MegasenaServiceServer).SimularSorteio(ctx, req.(*SimulacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MegasenaService_ServiceDesc is the grpc.ServiceDesc for MegasenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MegasenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "megasena.MegasenaService",
	HandlerType: (*MegasenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GerarAposta",
			Handler:    _MegasenaService_GerarAposta_Handler,
		},
		{
			MethodName: "SimularSorteio",
			Handler:    _MegasenaService_SimularSorteio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "megasena.proto",
}
