// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: megasena.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApostaRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QuantidadeDezenas int32                  `protobuf:"varint,1,opt,name=quantidade_dezenas,json=quantidadeDezenas,proto3" json:"quantidade_dezenas,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApostaRequest) Reset() {
	*x = ApostaRequest{}
	mi := &file_megasena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApostaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApostaRequest) ProtoMessage() {}

func (x *ApostaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_megasena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApostaRequest.ProtoReflect.Descriptor instead.
func (*ApostaRequest) Descriptor() ([]byte, []int) {
	return file_megasena_proto_rawDescGZIP(), []int{0}
}

func (x *ApostaRequest) GetQuantidadeDezenas() int32 {
	if x != nil {
		return x.QuantidadeDezenas
	}
	return 0
}

type ApostaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numeros       []int32                `protobuf:"varint,1,rep,packed,name=numeros,proto3" json:"numeros,omitempty"`
	DataGeracao   string                 `protobuf:"bytes,2,opt,name=data_geracao,json=dataGeracao,proto3" json:"data_geracao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApostaResponse) Reset() {
	*x = ApostaResponse{}
	mi := &file_megasena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApostaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApostaResponse) ProtoMessage() {}

func (x *ApostaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_megasena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApostaResponse.ProtoReflect.Descriptor instead.
func (*ApostaResponse) Descriptor() ([]byte, []int) {
	return file_megasena_proto_rawDescGZIP(), []int{1}
}

func (x *ApostaResponse) GetNumeros() []int32 {
	if x != nil {
		return x.Numeros
	}
	return nil
}

func (x *ApostaResponse) GetDataGeracao() string {
	if x != nil {
		return x.DataGeracao
	}
	return ""
}

type SimulacaoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DezenasAlvo   []int32                `protobuf:"varint,1,rep,packed,name=dezenas_alvo,json=dezenasAlvo,proto3" json:"dezenas_alvo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulacaoRequest) Reset() {
	*x = SimulacaoRequest{}
	mi := &file_megasena_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulacaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulacaoRequest) ProtoMessage() {}

func (x *SimulacaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_megasena_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulacaoRequest.ProtoReflect.Descriptor instead.
func (*SimulacaoRequest) Descriptor() ([]byte, []int) {
	return file_megasena_proto_rawDescGZIP(), []int{2}
}

func (x *SimulacaoRequest) GetDezenasAlvo() []int32 {
	if x != nil {
		return x.DezenasAlvo
	}
	return nil
}

type SimulacaoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalTentativas int64                  `protobuf:"varint,1,opt,name=total_tentativas,json=totalTentativas,proto3" json:"total_tentativas,omitempty"`
	TempoSegundos   float64                `protobuf:"fixed64,2,opt,name=tempo_segundos,json=tempoSegundos,proto3" json:"tempo_segundos,omitempty"`
	Numeros         []int32                `protobuf:"varint,3,rep,packed,name=numeros,proto3" json:"numeros,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulacaoResponse) Reset() {
	*x = SimulacaoResponse{}
	mi := &file_megasena_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulacaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulacaoResponse) ProtoMessage() {}

func (x *SimulacaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_megasena_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulacaoResponse.ProtoReflect.Descriptor instead.
func (*SimulacaoResponse) Descriptor() ([]byte, []int) {
	return file_megasena_proto_rawDescGZIP(), []int{3}
}

func (x *SimulacaoResponse) GetTotalTentativas() int64 {
	if x != nil {
		return x.TotalTentativas
	}
	return 0
}

func (x *SimulacaoResponse) GetTempoSegundos() float64 {
	if x != nil {
		return x.TempoSegundos
	}
	return 0
}

func (x *SimulacaoResponse) GetNumeros() []int32 {
	if x != nil {
		return x.Numeros
	}
	return nil
}

var File_megasena_proto protoreflect.FileDescriptor

const file_megasena_proto_rawDesc = "" +
	"\n" +
	"\x0emegasena.proto\x12\bmegasena\">\n" +
	"\rApostaRequest\x12-\n" +
	"\x12quantidade_dezenas\x18\x01 \x01(\x05R\x11quantidadeDezenas\"M\n" +
	"\x0eApostaResponse\x12\x18\n" +
	"\anumeros\x18\x01 \x03(\x05R\anumeros\x12!\n" +
	"\fdata_geracao\x18\x02 \x01(\tR\vdataGeracao\"5\n" +
	"\x10SimulacaoRequest\x12!\n" +
	"\fdezenas_alvo\x18\x01 \x03(\x05R\vdezenasAlvo\"\x7f\n" +
	"\x11SimulacaoResponse\x12)\n" +
	"\x10total_tentativas\x18\x01 \x01(\x03R\x0ftotalTentativas\x12%\n" +
	"\x0etempo_segundos\x18\x02 \x01(\x01R\rtempoSegundos\x12\x18\n" +
	"\anumeros\x18\x03 \x03(\x05R\anumeros2\x9e\x01\n" +
	"\x0fMegasenaService\x12@\n" +
	"\vGerarAposta\x12\x17.megasena.ApostaRequest\x1a\x18.megasena.ApostaResponse\x12I\n" +
	"\x0eSimularSorteio\x12\x1a.megasena.SimulacaoRequest\x1a\x1b.megasena.SimulacaoResponseBBZ\x15megasena-server/proto\xca\x02\x11App\\Grpc\\Megasena\xe2\x02\x14App\\Grpc\\GPBMetadatab\x06proto3"

var (
	file_megasena_proto_rawDescOnce sync.Once
	file_megasena_proto_rawDescData []byte
)

func file_megasena_proto_rawDescGZIP() []byte {
	file_megasena_proto_rawDescOnce.Do(func() {
		file_megasena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_megasena_proto_rawDesc), len(file_megasena_proto_rawDesc)))
	})
	return file_megasena_proto_rawDescData
}

var file_megasena_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_megasena_proto_goTypes = []any{
	(*ApostaRequest)(nil),     // 0: megasena.ApostaRequest
	(*ApostaResponse)(nil),    // 1: megasena.ApostaResponse
	(*SimulacaoRequest)(nil),  // 2: megasena.SimulacaoRequest
	(*SimulacaoResponse)(nil), // 3: megasena.SimulacaoResponse
}
var file_megasena_proto_depIdxs = []int32{
	0, // 0: megasena.MegasenaService.GerarAposta:input_type -> megasena.ApostaRequest
	2, // 1: megasena.MegasenaService.SimularSorteio:input_type -> megasena.SimulacaoRequest
	1, // 2: megasena.MegasenaService.GerarAposta:output_type -> megasena.ApostaResponse
	3, // 3: megasena.MegasenaService.SimularSorteio:output_type -> megasena.SimulacaoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_megasena_proto_init() }
func file_megasena_proto_init() {
	if File_megasena_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_megasena_proto_rawDesc), len(file_megasena_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_megasena_proto_goTypes,
		DependencyIndexes: file_megasena_proto_depIdxs,
		MessageInfos:      file_megasena_proto_msgTypes,
	}.Build()
	File_megasena_proto = out.File
	file_megasena_proto_goTypes = nil
	file_megasena_proto_depIdxs = nil
}
